# Generated by Django 5.0.6 on 2024-07-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportschedules',
            name='vehicles',
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('booking', 'seat_number')},
        ),
    ]
