# Generated by Django 5.0.6 on 2024-07-13 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transportschedules_vehicles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedbooking',
            name='bus_schedule',
        ),
        migrations.AddField(
            model_name='fixedbooking',
            name='bus_and_schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.transportbusesandschedules'),
            preserve_default=False,
        ),
    ]
