# Generated by Django 5.0.6 on 2024-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_busschedule_remove_review_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
