# Generated by Django 5.0.6 on 2024-07-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transportbus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportbusesandschedules',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='transportbusesandschedules',
            name='transportbus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transportbus'),
        ),
    ]
