# Generated by Django 5.0.6 on 2024-07-14 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_transportbusesandschedules_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportbusesandschedules',
            name='transportbus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.transportbus'),
            preserve_default=False,
        ),
    ]
