# Generated by Django 5.0.6 on 2024-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transportbusesandschedules_transportbus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Truck', 'Truck'), ('SUV', 'SUV')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, choices=[('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Ford', 'Ford'), ('BMW', 'BMW')], max_length=255, null=True),
        ),
    ]
