# Generated by Django 5.0.6 on 2024-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_flexiblebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, choices=[('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Ford', 'Ford'), ('BMW', 'BMW')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Truck', 'Truck'), ('SUV', 'SUV')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
