# Generated by Django 5.0.6 on 2024-07-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vehicleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
    ]
