# Generated by Django 5.0.6 on 2024-07-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fixedbooking_cost_fixedbooking_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedbooking',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flexiblebooking',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
