# Generated by Django 5.0.6 on 2024-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alert', 'Alert'), ('reminder', 'Reminder'), ('update', 'Update'), ('message', 'Message')], default='alert', max_length=255),
        ),
    ]
