# Generated by Django 5.0.6 on 2024-06-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('contact', models.TextField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
