# Generated by Django 5.0.6 on 2024-06-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('brand', models.TextField(max_length=50)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drivers.drivers')),
            ],
        ),
    ]
